{/* <ApplicationModal open={modalOpen} onClose={handleCloseModal} data={{
        company: row.company,
        position: row.position,
        interest_level: row.interest_level,
        date_submitted: row.date_submitted,
        location: row.location,
        description: row.description,
        application_type: row.application_type,
        job_posting_url: row.job_posting_url,
        internal_contact: row.internal_contact,
        internal_contact_email: row.internal_contact_email,
        follow_up: row.follow_up,
        notes: row.notes,
        status: row.status,
      }} applicationId={row.id}/> */}